### ISSUE TITLE
Incorporate into Arduino..???/

### ISSUE THREAD

**Issue by davidabevan** [stevstrong/CDC-flasher#1]
Hi thanks for your input yesterday, am now able to upload the f303 via usb...
I am wondering as i am not particularly good at typing and remembering cli paths etc, just a tinkerer..
Can I modify my Arduino to run your script to upload that way so i can compile and upload all in 1 go..
If possible i would prob need help to setup, I have been experimenting uploading a lot of ili9341 sketches and compiling to hex file every time and using your bootloader works So am thinking this may work..
Thanks Dave....

**Comment by stevstrong** [comment]
In fact, it is already incorporated into the Arduino framework of my core.
The instructions can be found here: https://github.com/stevstrong/STM32-CDC-Bootloader/blob/master/F3/Readme.md

**Comment by davidabevan** [comment]
Brilliant Will check it out later today 👍

**Comment by davidabevan** [comment]
Hi can you advise please, bearing in mind i am just a hobbyist so to speak.
Am at this point in your instructions
Copy to variant directory the linker file:
the file  I have no idea where to put it.....

**Comment by stevstrong** [comment]
Which core do you use with Arduino?
[My core](https://github.com/stevstrong/Arduino_STM32) or [the official from ST](https://github.com/stm32duino/Arduino_Core_STM32)?

**Comment by davidabevan** [comment]
Ahh I believe I am running the official core.
I downloaded your CDC repo the cli upload script if u remember from my
question the other day to Rodger Clarke Melbourne.
I am kind of getting out of my depth but we all got to learn..
Thanks

**Comment by stevstrong** [comment]
I do not know for sure, but I think here would be the right place for it:
https://github.com/stm32duino/Arduino_Core_STM32/tree/master/variants/PILL_F303XX

The right place for the flasher you have to find out from the platform.txt checking other (e.g. HID upload) methods.

**Comment by davidabevan** [comment]
Ok thanks I will try and work this out.

**Comment by davidabevan** [comment]
Of course if it helps I can install your libraries maybe. Of course I
understand you must be busy and may not have time to advise a novice I
fully can understand.
Thanks for helping so far..
Dave

**Comment by stevstrong** [comment]
I just do not how the Arduino_Core_STM works, that is why I cannot tell you what to do.
You better ask for support in forum: www.stm32duino.com

**Comment by davidabevan** [comment]
No problems at all thanks 👍😁
