### ISSUE TITLE
Using arduino .bin file

### ISSUE THREAD

**Issue by Marcelocm1995** [stevstrong/CDC-flasher#2]
Hi, first: sorry for my english.
I used stlink to burn de bootloard bin file, works fine.
I export my F103 (bluepill) bin files from arduino to same path that I have cdc-flasher.exe.
I execute the CLI with "cdc-flasher.exe myfile.bin COM64 1", and prompt shows the progress download and done! but my code doesn't run e I lost the bootloader.

What I am doing wrong?

Thanks.

**Comment by stevstrong** [comment]
It does matter which upload option do you select in Arduino IDE when you build your project.
To use the CDC flasher you should use the "CDC bootloader" option, otherwise it will not work:

https://github.com/stevstrong/Arduino_STM32/blob/62a37fec36a3aa026d3873dc4fb08fb0481d56c1/STM32F1/boards.txt#L380-L384

Basically you need to link the sketch to start from flash address 0x08001000.

**Comment by Marcelocm1995** [comment]
I think that I don't understand, but I want to flash my firmware (.bin) without arduino IDE, only using cdc-flasher.exe

**Comment by stevstrong** [comment]
How do you generate your bluepill bin files?
You need to link your application to start from flash address 0x08001000.

**Comment by Marcelocm1995** [comment]
I used this metod
https://randomnerdtutorials.com/bin-binary-files-sketch-arduino-ide/

**Comment by stevstrong** [comment]
OK, so under the first step, which board have you selected?
Under Arduino menu "Tools", you have an option to select an upload method. Which method have you selected?

**Comment by Marcelocm1995** [comment]
generic stm32f103c series; variant stm32103CB(20Kb Ram, 126Kb flash); upload metod stm32duino bootloader

**Comment by stevstrong** [comment]
If you want to use CDC flasher with Arduino IDE, you have to do the followings:
- copy into the file `STM32F1/boards.txt` the [following lines](https://github.com/stevstrong/Arduino_STM32/blob/62a37fec36a3aa026d3873dc4fb08fb0481d56c1/STM32F1/boards.txt#L380-L384):

```
genericSTM32F103C.menu.upload_method.CDCUploadMethod=CDC bootloader 1.0
genericSTM32F103C.menu.upload_method.CDCUploadMethod.upload.tool=cdc_upload
genericSTM32F103C.menu.upload_method.CDCUploadMethod.build.upload_flags=-DSERIAL_USB -DGENERIC_BOOTLOADER
genericSTM32F103C.menu.upload_method.CDCUploadMethod.build.vect=VECT_TAB_ADDR=0x8001000
genericSTM32F103C.menu.upload_method.CDCUploadMethod.build.ldscript=ld/cdc_bootloader.ld
```
- copy into the file `STM32F1/platform.txt` [these lines](https://github.com/stevstrong/Arduino_STM32/blob/62a37fec36a3aa026d3873dc4fb08fb0481d56c1/STM32F1/platform.txt#L181-L190):
```
# CDC upload 1.0
tools.cdc_upload.cmd=cdc_upload
tools.cdc_upload.cmd.windows=cdc_upload.bat
tools.cdc_upload.path.windows={runtime.hardware.path}/tools/win
#tools.cdc_upload.path.macosx={runtime.hardware.path}/tools/macosx
#tools.cdc_upload.path.linux={runtime.hardware.path}/tools/linux
#tools.cdc_upload.path.linux64={runtime.hardware.path}/tools/linux64
tools.cdc_upload.upload.params.verbose=
tools.cdc_upload.upload.params.quiet=
tools.cdc_upload.upload.pattern="{path}/{cmd}" "{build.path}/{build.project_name}.bin" {serial.port.file} 1
```
- copy the file https://github.com/stevstrong/Arduino_STM32/blob/master/STM32F1/variants/generic_stm32f103c/ld/cdc_bootloader.ld to the folder `STM32F1/variants/generic_stm32f103c/ld/`

- restart Arduino IDE
- select upload method: `CDC bootloader 1.0`.

**Comment by Marcelocm1995** [comment]
Thank you, works perfectly!!!!!!!!!!
